### ISSUE TITLE
Add some cmdlets to interact with JMX

### ISSUE THREAD

**Issue by mariomastrodicasa** [masesgroup/JNet#110]
Seems JNetPS does not contain any cmdlet (see #50) to interact with JMX

_Originally posted by @mariomastrodicasa in https://github.com/masesgroup/JNet/issues/104#issuecomment-1411182279_

**Comment by masesdevelopers** [comment]
About _some cmdlets_, a proposal is to follow the example in https://docs.oracle.com/javase/tutorial/jmx/remote/custom.html to list a set of possible useful cmdlets.

**Comment by mariomastrodicasa** [comment]
@masesdevelopers I agree. Maybe some objects can be managed with `dynamic` feature.
