### ISSUE TITLE
Create the classes of Listener/Adapter and so on

### ISSUE THREAD

**Issue by masesdevelopers** [masesgroup/JNet#137]
>> So in first instance if a class name ends with `Listener` the tool can avoid its reflection, but in general a tool like JNetReflector cannot distinguish which interface, or class, shall be managed in different way only because it represents a callback.

>The previous will be implemented checking if the class name ends with `Listener` or `Adapter`, and will be added a command line switch `ClassesToBeListener` to list all classes which are events callback and be treated as a Listener. Anyway the implementation, till now, shall be done manually.

Remember to create the classes: now they are reported, during compilation, as a **warning**. The possible options are:
- create the classes manually
- find a way to build them automatically following a generation pattern

_Originally posted by @masesdevelopers in https://github.com/masesgroup/JNet/issues/130#issuecomment-1438719700_

**Comment by masesdevelopers** [comment]
Some classes can be created from JNetReflector checking if they inherit from any of the one manually made

**Comment by masesdevelopers** [comment]
> Some classes can be created from JNetReflector checking if they inherit from any of the one manually made

If a Class implements the Listener interfaces shall not be a Listener too.

**Comment by masesdevelopers** [comment]
Use always `JVMBridgeException` when there is an exception type in parameters to have an unified approach between listeners and methods

**Comment by masesdevelopers** [comment]
The following shall be made manually:  
- `java.util.Comparator`
- `java.util.ServiceLoader$Provider`

**Comment by masesdevelopers** [comment]
> The following shall be made manually:
> 
>     * `java.util.Comparator`
> 
>     * `java.util.ServiceLoader$Provider`

`java.util.ServiceLoader$Provider` will be avoid till now

**Comment by mariomastrodicasa** [comment]
@masesdevelopers PR #184 contains this sentence "MouseInputAdapter does not have generated C# counterpart", I reopen the issue
