### ISSUE TITLE
DoxFX is unable to create documentation

### ISSUE THREAD

**Issue by masesdevelopers** [masesgroup/JNet#35]
**Describe the bug**
The documentation is not generated 

**To Reproduce**
1. Run the **build.yaml**
2. Go to **Build documentation** step
3. Find the _[Failure] Msbuild failed when processing the file 'D:\a\JNet\JNet\src\net\JNet\JNet.csproj' with message: Method not found: 'System.ReadOnlySpan`1<Char> Microsoft.IO.Path.GetFileName(System.ReadOnlySpan`1<Char>)'._

**Expected behavior**
The documentation shall be generated

**Screenshots**
![image](https://user-images.githubusercontent.com/94312179/185495958-d39016c7-4bb7-4de7-9631-0574bd42fd14.png)

**Desktop (please complete the following information):**
 - OS: GitHub Virtual environment
 - Image Version: 20220816.1

**Additional context**
Seems the error is well known because it is an open issue of DocFX: https://github.com/dotnet/docfx/issues/8097

**Comment by mariomastrodicasa** [comment]
@masesdevelopers if the problem is related to the VS version within the Image version 20220816.1, is it possible to use an old image to run the workflows?

**Comment by masesdevelopers** [comment]
Found this transitory workaround https://github.com/dotnet/docfx/issues/8136#issuecomment-1219512721
