### ISSUE TITLE
Add reflection tool

### ISSUE THREAD

**Issue by masesdevelopers** [masesgroup/JNet#45]
**Is your feature request related to a problem? Please describe.**
To write base classes it is tedious. A tool to reflect classes from Java can be useful.

**Describe the solution you'd like**
Write a tool able to create classes reading the JARs.
At least, for each JAR and package, can be useful to:
- for each package create a folder structure corresponding to the package name
- have an auto-generated file with all partial classes defining the class
- create many files named like the class that can extend the base class

**Describe alternatives you've considered**
N/A

**Additional context**
Something like the tool available in [JCOReflector](https://github.com/masesgroup/JCOReflector)

**Comment by mariomastrodicasa** [comment]
@masesdevelopers The tool does not report anything in console or file about its execution. See what [JCOReflector](https://github.com/masesgroup/JCOReflector) does.

**Comment by mariomastrodicasa** [comment]
@masesdevelopers, generics are avoided and it is ok. Anyway it is possible to add the base class of generics like in [Map](https://github.com/masesgroup/JNet/blob/5d12af96053a7dd031bf7ff88458d26ccafcbe94/src/net/JNet/Java/Util/Map.cs). In this way the method which does not need the generics parameters can be implemented.

**Comment by mariomastrodicasa** [comment]
@masesdevelopers I will create an issue to track generation of generics from JNetReflector.
