### ISSUE TITLE
Missing jars in deployed PowerShell module

### ISSUE THREAD

**Issue by mariomastrodicasa** [masesgroup/JNet#60]
**Describe the bug**
Within the binary folder the jars are missed

**Expected behavior**
The folders net6.0 and net462 shall contains the needed jars like nuget packages have

**Screenshots**
No screenshoot, see list of FileList on https://www.powershellgallery.com/packages/MASES.JNetPS/1.4.11

**Desktop (please complete the following information):**
 - OS: All
 - Version 1.4.11

**Additional context**
N/A

**Comment by masesdevelopers** [comment]
Linked to #64
