### ISSUE TITLE
KNet needs some classes from JNet

### ISSUE THREAD

**Issue by masesdevelopers** [masesgroup/JNet#75]
**Is your feature request related to a problem? Please describe.**
Some classes in KNet needs that JNet implements more classes.

**Describe the solution you'd like**
Adds needed classes. At least check the following:
- https://github.com/masesgroup/KNet/blob/ebeb28484e503daa93945810fb4ad6d3303f9ef6/src/net/KNet/ClientSide/BridgedClasses/Connect/Rest/Basic/Auth/Extension/PropertyFileLoginModule.cs#L29
- https://github.com/masesgroup/KNet/blob/ebeb28484e503daa93945810fb4ad6d3303f9ef6/src/net/KNet/ClientSide/BridgedClasses/Connect/Rest/ConnectRestExtensionContext.cs#L29
- https://github.com/masesgroup/KNet/blob/ebeb28484e503daa93945810fb4ad6d3303f9ef6/src/net/KNet/ClientSide/BridgedClasses/Connect/Rest/Basic/Auth/Extension/BasicAuthSecurityRestExtension.cs#L28
- https://github.com/masesgroup/KNet/blob/ebeb28484e503daa93945810fb4ad6d3303f9ef6/src/net/KNet/ClientSide/BridgedClasses/Connect/Rest/Basic/Auth/Extension/JaasBasicAuthFilter.cs#L28

**Describe alternatives you've considered**
Until now the class can be used thanks to Dynamic Language Runtime capability.

**Additional context**
N/A

**Comment by mariomastrodicasa** [comment]
The class list refers to Apache Kafka Connect, but maybe are not used in KNet Connect SDK
